### ISSUE TITLE
ValueError: _lbfgsb._lbfgsb.setulb: failed to create array from the 10th argument `wa` -- 0-th dimension must be fixed to 666123109 but got 4961090405 [bug]

### ISSUE THREAD

**Issue by UnixJunkie** [lcmd-epfl/MLKRR#10]
```Optimizing for sigma. Current sigma: 1.0
New sigma: 1.0 (took 32.67 s)
Traceback (most recent call last):
  File "/home/fbr/src/fp_bench/./rfr.py", line 273, in <module>
    r2 = mlkrr_train_test_UCAP(train_fn, test_fn)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fbr/src/fp_bench/./rfr.py", line 181, in mlkrr_train_test_UCAP
    model.fit(X_train, y_train)
  File "/home/fbr/src/fp_bench/mlkrr.py", line 213, in fit
    res = minimize(
          ^^^^^^^^^
  File "/usr/lib/python3/dist-packages/scipy/optimize/_minimize.py", line 710, in minimize
    res = _minimize_lbfgsb(fun, x0, args, jac, bounds,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/scipy/optimize/_lbfgsb_py.py", line 356, in _minimize_lbfgsb
    _lbfgsb.setulb(m, x, low_bnd, upper_bnd, nbd, f, g, factr,
ValueError: _lbfgsb._lbfgsb.setulb: failed to create array from the 10th argument `wa` -- 0-th dimension must be fixed to 666123109 but got 4961090405```

**Comment by UnixJunkie** [comment]
Did you ever saw this while trying to fit a model?

**Comment by raimon-fa** [comment]
I can't remember finding such an error. What is the shape of data you are using to train? How many data points and how many features?

**Comment by UnixJunkie** [comment]
160 datapoints in the training set.
4428 features each.

**Comment by raimon-fa** [comment]
I don't think this is the cause of you error. Nevertheless, I think you will severely overfit with such a big feature space and few samples. Maybe you can prefilter the feature space.

**Comment by UnixJunkie** [comment]
You have a regularization parameter, can't I control it to prevent
overfitting?
i.e. use stronger regularization

**Comment by UnixJunkie** [comment]
This error might have been caused by lack of RAM on the computer where I was trying.
I might confirm this soon.

**Comment by UnixJunkie** [comment]
This also happen in a very high memory compute cluster node; so available memory is not the issue here.

**Comment by UnixJunkie** [comment]
Are there some limitations I don't know even after having read the paper, like a matrix w/ only positive integer values might be problematic?

**Comment by UnixJunkie** [comment]
Are the features supposed to be 0-centered and have unit variance?

**Comment by UnixJunkie** [comment]
Cc. @puckvg

**Comment by raimon-fa** [comment]
No issues with only positive integer values, and there are no algorithmic restrictions related to the variance, although it it probably a good idea to normalize your features before.

**Comment by raimon-fa** [comment]
The regularization might help with overfitting but we did not test it extensively.

**Comment by UnixJunkie** [comment]
The Iris dataset that is used as en example does not have zero mean and unit variance, but MLKRR can work on it.

**Comment by UnixJunkie** [comment]
I will try lowering the dimensionality of my dataset (keeping only the most frequent 720 features).

**Comment by UnixJunkie** [comment]
Current implementation works up to 1500 dimensions.
starting from 1550 dimensions, it will crash.
